"""empty message

Revision ID: 76ec99861b87
Revises: c5f0a2b3d7e8
Create Date: 2026-05-16 22:30:18.650768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76ec99861b87'
down_revision = 'c5f0a2b3d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_profiles')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('cleaner_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('fk_cleaner'))

    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.drop_column('supplier')

    with op.batch_alter_table('supply_inventory', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('Order', 'Stock Taken', 'Adjustment'),
               nullable=True,
               existing_server_default=sa.text("'Order'"))
        batch_op.drop_constraint(batch_op.f('fk_supply_inventory_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['taken_by_user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', mysql.LONGTEXT(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('supply_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_supply_inventory_user'), 'user', ['taken_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('transaction_type',
               existing_type=mysql.ENUM('Order', 'Stock Taken', 'Adjustment'),
               nullable=False,
               existing_server_default=sa.text("'Order'"))
        batch_op.alter_column('vendor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', mysql.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_cleaner'), ['cleaner_id'], unique=False)
        batch_op.alter_column('cleaner_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('house_profiles',
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_codes', mysql.TINYBLOB(), nullable=True),
    sa.Column('pet_notes', mysql.TEXT(), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_contacts.customer_id'], name=op.f('fk_house_customer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
