"""Create supplies table

Revision ID: 81b685cace75
Revises: e8a173289aa8
Create Date: 2026-05-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81b685cace75'
down_revision = 'e8a173289aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('minimum_threshold', sa.Integer(), nullable=False, server_default=sa.text('5')),
    sa.Column('unit', sa.String(length=20), nullable=False, server_default=sa.text("'units'")),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('last_restocked', sa.DateTime(), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies')
    # ### end Alembic commands ###
