"""Update supplies table with vendor relationship

Revision ID: a3d8e9f2b1c4
Revises: 92c756dfb1a8
Create Date: 2026-05-15 10:10:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a3d8e9f2b1c4'
down_revision = '92c756dfb1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_supplies_preferred_vendor'), 'vendors', ['preferred_vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplies_preferred_vendor'), type_='foreignkey')
        batch_op.drop_column('preferred_vendor_id')
    # ### end Alembic commands ###
