"""initial baseline with tracking flag

Revision ID: a86309d493f6
Revises: 
Create Date: 2026-05-23 22:45:18.511796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a86309d493f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_audit')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=False))
        batch_op.drop_constraint(batch_op.f('appointments_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('cost')
        batch_op.drop_column('paid_date')
        batch_op.drop_column('actual_start_time')

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_column('address')
        batch_op.drop_column('city')
        batch_op.drop_column('email')
        batch_op.drop_column('state')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('property_nickname')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('property_nickname', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=True))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_start_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('paid_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('cost', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_foreign_key(batch_op.f('appointments_ibfk_1'), 'customer_contacts', ['customer_id'], ['customer_id'])
        batch_op.drop_column('reminder_sent')

    op.create_table('inventory_audit',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supply_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audit_type', mysql.ENUM('Discrepancy Found', 'Manual Correction', 'Reconciliation', 'Validation Failed'), nullable=False),
    sa.Column('previous_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('calculated_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', mysql.TEXT(), nullable=True),
    sa.Column('corrected_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['user.id'], name=op.f('inventory_audit_ibfk_2')),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], name=op.f('inventory_audit_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
