"""Rename supply_orders to supply_inventory and add stock tracking fields

Revision ID: c5f0a2b3d7e8
Revises: b4e9f1a2c5d6
Create Date: 2026-05-15 10:20:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c5f0a2b3d7e8'
down_revision = 'b4e9f1a2c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the table
    op.rename_table('supply_orders', 'supply_inventory')
    
    # Add new columns to track usage
    with op.batch_alter_table('supply_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.Enum('Order', 'Stock Taken', 'Adjustment'), server_default=sa.text("'Order'"), nullable=False))
        batch_op.add_column(sa.Column('taken_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('taken_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(255), nullable=True))
        batch_op.add_column(sa.Column('quantity_remaining', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_supply_inventory_user'), 'user', ['taken_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supply_inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supply_inventory_user'), type_='foreignkey')
        batch_op.drop_column('quantity_remaining')
        batch_op.drop_column('reason')
        batch_op.drop_column('taken_at')
        batch_op.drop_column('taken_by_user_id')
        batch_op.drop_column('transaction_type')
    
    op.rename_table('supply_inventory', 'supply_orders')
    # ### end Alembic commands ###
