"""empty message

Revision ID: e8a173289aa8
Revises: ed2fc115825c
Create Date: 2026-05-14 21:00:13.367437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8a173289aa8'
down_revision = 'ed2fc115825c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables only if they exist
    try:
        op.drop_table('payments')
    except:
        pass
    
    try:
        op.drop_table('house_profiles')
    except:
        pass
    
    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('username'))
    except:
        pass

    try:
        op.drop_table('users')
    except:
        pass
    
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('scheduled_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        try:
            batch_op.drop_constraint(batch_op.f('fk_cleaner'), type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_constraint(batch_op.f('fk_customer_contact'), type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_constraint(batch_op.f('appointments_ibfk_1'), type_='foreignkey')
        except:
            pass
        try:
            batch_op.drop_column('service_rate')
        except:
            pass
        try:
            batch_op.drop_column('profile_id')
        except:
            pass
        try:
            batch_op.drop_column('actual_start_time')
        except:
            pass
        try:
            batch_op.drop_column('user_id')
        except:
            pass

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        try:
            batch_op.drop_column('created_at')
        except:
            pass
        try:
            batch_op.drop_column('street_address')
        except:
            pass
        try:
            batch_op.drop_column('city')
        except:
            pass
        try:
            batch_op.drop_column('zip_code')
        except:
            pass
        try:
            batch_op.drop_column('last_name')
        except:
            pass
        try:
            batch_op.drop_column('phone_number')
        except:
            pass
        try:
            batch_op.drop_column('email_address')
        except:
            pass
        try:
            batch_op.drop_column('first_name')
        except:
            pass
        try:
            batch_op.drop_column('updated_at')
        except:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email_address', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('zip_code', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('street_address', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('actual_start_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('profile_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_rate', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(batch_op.f('appointments_ibfk_1'), 'house_profiles', ['profile_id'], ['profile_id'])
        batch_op.create_foreign_key(batch_op.f('fk_customer_contact'), 'customer_contacts', ['user_id'], ['customer_id'])
        batch_op.create_foreign_key(batch_op.f('fk_cleaner'), 'users', ['cleaner_id'], ['user_id'])
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('scheduled_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('public_key', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    op.create_table('house_profiles',
    sa.Column('profile_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_codes', mysql.TINYBLOB(), nullable=True),
    sa.Column('pet_notes', mysql.TEXT(), nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_contacts.customer_id'], name='fk_house_customer', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('apt_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stripe_transaction_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', mysql.ENUM('Pending', 'Authorized', 'Paid', 'Failed'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['apt_id'], ['appointments.apt_id'], name=op.f('payments_ibfk_1')),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
