"""Add all models and update role enum

Revision ID: ed2fc115825c
Revises: 
Create Date: 2026-05-06 15:40:17.137155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed2fc115825c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update existing role values to match new enum
    op.execute("UPDATE users SET role = 'office' WHERE role = 'OfficeAdmin'")
    op.execute("UPDATE users SET role = 'cleaner' WHERE role = 'Cleaner'")
    op.execute("UPDATE users SET role = 'customer' WHERE role = 'BusinessOwner'")
    
    # Then alter the column to use the new enum values
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('admin', 'cleaner', 'office', 'customer', 'observer') NOT NULL DEFAULT 'customer'")
    
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_scheduled_time'))
        batch_op.drop_table_comment(
        existing_comment='Stores core appointment data including quoted service_rate for billing transparency.'
    )

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('house_profiles', schema=None) as batch_op:
        batch_op.alter_column('entry_codes',
               existing_type=sa.VARBINARY(length=255),
               type_=sa.LargeBinary(length=255),
               existing_nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert role values to original enum
    op.execute("UPDATE users SET role = 'OfficeAdmin' WHERE role = 'office' OR role = 'admin'")
    op.execute("UPDATE users SET role = 'Cleaner' WHERE role = 'cleaner'")
    op.execute("UPDATE users SET role = 'BusinessOwner' WHERE role = 'customer' OR role = 'observer'")
    
    # Alter column back to original enum
    op.execute("ALTER TABLE users MODIFY COLUMN role ENUM('OfficeAdmin','Cleaner','BusinessOwner') NOT NULL")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('house_profiles', schema=None) as batch_op:
        batch_op.alter_column('entry_codes',
               existing_type=sa.LargeBinary(length=255),
               type_=sa.VARBINARY(length=255),
               existing_nullable=True)

    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores core appointment data including quoted service_rate for billing transparency.',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_scheduled_time'), ['scheduled_time'], unique=False)

    # ### end Alembic commands ###
